#!/usr/bin/env bash

set -e

output="$1"

help() {
  echo "Usage: $(basename $0) OUTPUT_DIR"
  echo "  Takes the json file on stdin (generated by get-places.sh) and saves"
  echo "  items to OUTPUT_DIR (making directory if necessary).  Then polls gets"
  echo "  PageShot representation as necessary in OUTPUT_DIR"
}

if [ -z "$output" ] ; then
  echo "Error: no OUTPUT_DIR given"
  help
  exit 2
fi

if [ ! -d "$output" ] ; then
  if [ -e "$output" ] ; then
    echo "Error: $output must be a directory, not a file"
    help
    exit 2
  fi
  mkdir -p "$output"
fi

python -c '
import sys
import json
import os
import sha

output_dir = sys.argv[1]

data = json.load(sys.stdin)
for page in data:
    url = page["url"]
    fn = os.path.join(output_dir, sha.new(url).hexdigest())
    if os.path.exists(fn):
        with open(fn) as fp:
            existing = json.load(fp)
        existing.update(page)
        page = existing
    with open(fn, "w") as fp:
        fp.write(json.dumps(page, indent=2))
' "$output"
